export const dashboardData = {
  school_info: {
    name: "Greenwood Elementary School",
    admin: {
      name: "School Admin",
      email: "admin@example.com",
      phone: "+1-555-0123",
      avatar: "G",
    },
    board: "CBSE Board",
    last_updated: "12/08/2025, 15:46:57",
  },

  // ------------------ Dashboard Overview ------------------
  dashboard_overview: {
    total_students: {
      count: 245,
      growth: "+12%",
    },
    total_classes: {
      count: 8,
      growth: "+8%",
    },
    avg_performance: {
      percentage: 86.2,
      growth: "+5%",
    },
    top_performer: {
      name: "Ahan K.",
      // class: "Class 8",
      points: 830,
    },
  },

  // ------------------ Class-wise Enrollment ------------------
  class_enrollment: [
    { class: "Class 1", students: 27 },
    { class: "Class 2", students: 36 },
    { class: "Class 3", students: 32 },
    { class: "Class 4", students: 28 },
    { class: "Class 5", students: 31 },
    { class: "Class 6", students: 29 },
    { class: "Class 7", students: 33 },
    { class: "Class 8", students: 29 },
  ],

  // ------------------ Performance Distribution ------------------
  performance_distribution: [
    { category: "Excellent (90-100%)", percentage: 20, color: "#4CAF50" },
    { category: "Good (80-89%)", percentage: 45, color: "#2196F3" },
    { category: "Average (70-79%)", percentage: 25, color: "#FF9800" },
    { category: "Needs Improvement", percentage: 10, color: "#f44336" },
  ],

  // ------------------ Leaderboard ------------------
  leaderboard: [
    {
      rank: 1,
      name: "Ahan Kumar",
      class: "Class 8",
      points: 830,
      accuracy: 96,
      streak: 15,
      lessons: 68,
      avatar: "HV",
    },
    {
      rank: 2,
      name: "Hvff",
      class: "Class 7",
      points: 295,
      accuracy: 94,
      streak: 12,
      lessons: 45,
      avatar: "H",
    },
    {
      rank: 3,
      name: "Flower Girl",
      class: "Class 6",
      points: 190,
      accuracy: 93,
      streak: 8,
      lessons: 38,
      avatar: "FG",
    },
    {
      rank: 4,
      name: "12 June Child Test",
      class: "Class 5",
      points: 165,
      accuracy: 92,
      streak: 6,
      lessons: 32,
      avatar: "JC",
    },
    {
      rank: 5,
      name: "Hcdff",
      class: "Class 4",
      points: 160,
      accuracy: 91,
      streak: 5,
      lessons: 30,
      avatar: "H",
    },
    {
      rank: 6,
      name: "Eva",
      class: "Class 3",
      points: 145,
      accuracy: 90,
      streak: 4,
      lessons: 28,
      avatar: "E",
    },
    {
      rank: 7,
      name: "Sophia Kim",
      class: "Class 2",
      points: 138,
      accuracy: 89,
      streak: 7,
      lessons: 26,
      avatar: "SK",
    },
    {
      rank: 8,
      name: "James Wilson",
      class: "Class 6",
      points: 132,
      accuracy: 88,
      streak: 3,
      lessons: 24,
      avatar: "JW",
    },
    {
      rank: 9,
      name: "Olivia Davis",
      class: "Class 5",
      points: 128,
      accuracy: 87,
      streak: 9,
      lessons: 22,
      avatar: "OD",
    },
    {
      rank: 10,
      name: "Liam Garcia",
      class: "Class 1",
      points: 120,
      accuracy: 86,
      streak: 2,
      lessons: 20,
      avatar: "LG",
    },
    {
      rank: 11,
      name: "Alex Thompson",
      class: "Class 7",
      points: 118,
      accuracy: 85,
      streak: 3,
      lessons: 19,
      avatar: "AT",
    },
    {
      rank: 12,
      name: "Maya Singh",
      class: "Class 6",
      points: 115,
      accuracy: 84,
      streak: 2,
      lessons: 18,
      avatar: "MS",
    },
  ],

  // ------------------ All Students ------------------
  all_students: [
    {
      id: 1,
      name: "Ahan Kumar",
      class: "Class 8",
      accuracy: 96,
      points: 830,
      avatar: "HV",
    },
    {
      id: 2,
      name: "Hvff",
      class: "Class 7",
      accuracy: 94,
      points: 295,
      avatar: "H",
    },
    {
      id: 3,
      name: "Flower Girl",
      class: "Class 6",
      accuracy: 93,
      points: 190,
      avatar: "FG",
    },
    {
      id: 4,
      name: "12 June Child Test",
      class: "Class 5",
      accuracy: 92,
      points: 165,
      avatar: "JC",
    },
    {
      id: 5,
      name: "Hcdff",
      class: "Class 4",
      accuracy: 91,
      points: 160,
      avatar: "H",
    },
    {
      id: 6,
      name: "Eva",
      class: "Class 3",
      accuracy: 90,
      points: 145,
      avatar: "E",
    },
    {
      id: 7,
      name: "Sophia Kim",
      class: "Class 2",
      accuracy: 89,
      points: 138,
      avatar: "SK",
    },
    {
      id: 8,
      name: "James Wilson",
      class: "Class 6",
      accuracy: 88,
      points: 132,
      avatar: "JW",
    },
    {
      id: 9,
      name: "Olivia Davis",
      class: "Class 5",
      accuracy: 87,
      points: 128,
      avatar: "OD",
    },
    {
      id: 10,
      name: "Liam Garcia",
      class: "Class 1",
      accuracy: 86,
      points: 120,
      avatar: "LG",
    },
    {
      id: 11,
      name: "Ava Martinez",
      class: "Class 3",
      accuracy: 85,
      points: 100,
      avatar: "AM",
    },
    {
      id: 12,
      name: "Noah Thompson",
      class: "Class 4",
      accuracy: 83,
      points: 95,
      avatar: "NT",
    },
  ],

  // ------------------ Analytics ------------------
  analytics: {
    total_learning_hours: { value: 2847, growth: "+12% from last month" },
    lessons_completed: { value: 1892, growth: "+18% from last month" },
    average_session_time: { value: "24 min", growth: "+8% from last month" },
    active_students: { value: 1156, growth: "+5% from last month" },

    performance_by_skill: [
      { skill: "Vocabulary", percentage: 82, improvement: "+5%" },
      { skill: "Grammar", percentage: 78, improvement: "+8%" },
      { skill: "Pronunciation", percentage: 76, improvement: "+12%" },
      { skill: "Listening", percentage: 85, improvement: "+3%" },
      { skill: "Speaking", percentage: 74, improvement: "+15%" },
    ],

    engagement_trends: [
      { month: "Jan", hours: 45 },
      { month: "Feb", hours: 52 },
      { month: "Mar", hours: 48 },
      { month: "Apr", hours: 55 },
      { month: "May", hours: 60 },
      { month: "Jun", hours: 58 },
    ],
  },

  // ------------------ Settings ------------------
  settings: {
    profile: {
      full_name: "Admin User",
      email: "admin@example.com",
      phone: "+1-555-0123",
    },
    system: {
      default_language: "English",
      time_zone: "UTC-5 (Eastern Time)",
    },
    notifications: {
      email_notifications: true,
      performance_reports: true,
      new_school_alerts: true,
    },
    data_management: {
      last_backup: "March 15, 2024",
    },
  },

  // ------------------ Achievements ------------------
  achievements: {
    top_scorer: { name: "Ahan Kumar", points: 830 },
    longest_streak: { name: "Ahan Kumar", days: 15 },
    most_lessons: { name: "Ahan Kumar", count: 68 },
    highest_accuracy: { name: "Ahan Kumar", percentage: 96 },
  },
};
